baseURL = "https://openwebcraft.com/"
LanguageCode = "en_US"
title = "openwebcraft.com"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "pages"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
PygmentsCodeFences = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "I want the web to win as a platform. — Matthias Geisler"
  facebook = ""
  twitter = "https://twitter.com/matthiasgeisler"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/norway_runde.jpg"

  [menus]
  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 1
  [[menu.main]]
      name = "Book"
      url = "/semantic-web-schnell-kompakt/"
      weight = 2
  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 3
  [[menu.main]]
      name = "Notes"
      url = "/notes/"
      weight = 4
  [[menu.main]]
      name = "Now"
      url = "/now/"
      weight = 5

 [[menu.footer]]
      name = "Datenschutz"
      url = "/privacy/"
      weight = 1
 [[menu.footer]]
      name = "Impressum"
      url = "/impressum/"
      weight = 2
 [[menu.footer]]
      name = "Contact"
      url = "/contact/"
      weight = 3