[build]
  command = "git submodule update --init --recursive --depth=1 && hugo --cleanDestinationDir --minify"
  publish = "public"
  environment = { HUGO_ENV = "production" }

[context.deploy-preview.environment]
  HUGO_VERSION = "0.57.2"

[context.production.environment]
  HUGO_VERSION = "0.57.2"

[[redirects]]
  from = "https://openwebcraft-com.netlify.com/*"
  to = "https://openwebcraft.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404