# Page Settings
title: Page

# Page Options
options:
    changeSlug: true
    changeStatus: true
    changeTitle: true
    delete: true
    preview: true
    read: true
    update: true
    preview: "/kirby/preview{{ page.parent.url }}/{{ page.slug }}"

# Available Statuses for the page
status:
    # Draft
    draft:
        label: Draft
        text: The page is still in draft mode. Only you can see it.

    # Unlisted Page
    unlisted:
        label: Private
        text: This page is online and can be visited with the direct URL.

    # Published Page
    listed:
        label: Public
        text: The page is online and listed in the footer.

# The Columns on the page
columns:
    - width: 1/1
      fields:
          staticSiteComposer:
             label: Compose Site

    # Left column. Contains the content pf the page
    - width: 2/3
      sections:
          main:
              extends: sections/main

    # Right Column. Contains the meta informations
    - width: 1/3
      sections:
          # Pictures
          pictures:
              extends: sections/pictures

          # Menu Informations
          extra:
              type: fields
              fields:
                  menu:
                      label: Menu Label
                      type: text
                      counter: false
                      help: >
                          Menu label used in the footer menu
        
          # Kirby Git 
          changes:
              type: git
              headline: Git Status