# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "owconbsd Theme"
license = "MIT"
licenselink = "https://github.com/openwebcraft.com/gohugo-theme-owconbsd/blob/master/LICENSE.md"
description = "A opinionated theme for building simple Hugo blog sites"
homepage = "https://openwebcraft.com/"
tags = ["website", "blog"]
features = ["posts", "shortcodes"]
min_version = 0.18

[author]
  name = "Matthias Geisler"
  homepage = "https://openwebcraft.com/"
